# Generated by Django 6.0.6 on 2026-07-19 15:36

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_company_is_active_alter_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrowthSkillFallback",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("growth_percentage", models.IntegerField(default=10)),
                ("median_salary", models.IntegerField(default=120000)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "high_growth_skill_fallbacks",
            },
        ),
        migrations.CreateModel(
            name="LocationLookup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("cities", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "location_lookups",
            },
        ),
        migrations.CreateModel(
            name="MarketRegionConfig",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("fallback_value", models.IntegerField(default=100)),
                ("color_hex", models.CharField(default="#2563EB", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "market_trend_regions",
            },
        ),
        migrations.CreateModel(
            name="SalaryTimelineConfig",
            fields=[
                (
                    "year",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("salary_k", models.IntegerField()),
                ("is_projection", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "historical_salary_timeline",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("period", models.CharField(default="month", max_length=20)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("limits", models.JSONField(default=dict)),
                ("features", models.JSONField(default=list)),
                ("target_portal", models.CharField(default="recruiter", max_length=50)),
                ("quota_description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "subscription_plans",
            },
        ),
    ]
