# Generated by Django 6.0.6 on 2026-07-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_seed_initial_config_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingsubscription",
            name="plan_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companybillingsubscription",
            name="plan_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seekerbillingsubscription",
            name="plan_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
