# Generated by Django 6.0.6 on 2026-07-19 15:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_billingsubscription_plan_snapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("status", models.CharField(default="open", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "support_tickets",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="is_banned",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="jobseekeraccount",
            name="is_banned",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
