# Generated by Django 6.0.6 on 2026-07-19 16:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_supportticket_company_is_banned_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminBanLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("admin_email", models.CharField(max_length=255)),
                ("target_type", models.CharField(max_length=50)),
                ("target_id", models.UUIDField()),
                ("action", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "admin_ban_logs",
            },
        ),
        migrations.AddField(
            model_name="developeraccount",
            name="is_banned",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="resolved_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="user_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
