# Generated by Django 6.0.6 on 2026-07-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_update_seeker_billing_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="messages",
            field=models.JSONField(default=list),
        ),
    ]
