# Generated by Django 6.0.6 on 2026-07-24 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_review_multi_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_company_reviews",
                to="api.company",
            ),
        ),
    ]
