# Generated by Django 6.0.6 on 2026-07-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_alter_review_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="jobseekeraccount",
            name="avatar_path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
