# Generated by Django 6.0.6 on 2026-07-24 07:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_alter_avatar_path_to_textfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="notification_settings",
            field=models.JSONField(
                default=api.models.default_company_notification_settings
            ),
        ),
    ]
