# Generated by Django 6.0.6 on 2026-07-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_reset_company_rating_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="developeraccount",
            name="avatar_path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="developeraccount",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="developeraccount",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
