# Generated by Django 6.0.6 on 2026-07-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_developeraccount_avatar_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="official_reply",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="official_reply_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
