# Generated by Django 6.0.6 on 2026-07-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_review_official_reply_review_official_reply_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        help_text="Internal agent identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, help_text="Human-readable name", max_length=100
                    ),
                ),
                (
                    "primary_provider",
                    models.CharField(
                        choices=[
                            ("gemini", "Gemini 2.5 Flash"),
                            ("groq", "Groq Llama 3.3 70B"),
                        ],
                        default="groq",
                        max_length=20,
                    ),
                ),
                (
                    "fallback_provider",
                    models.CharField(
                        choices=[
                            ("gemini", "Gemini 2.5 Flash"),
                            ("groq", "Groq Llama 3.3 70B"),
                        ],
                        default="gemini",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "agent_model_config",
                "ordering": ["agent_name"],
            },
        ),
        migrations.CreateModel(
            name="GeminiProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "daily_limit",
                    models.IntegerField(
                        default=20,
                        help_text="Max requests per day (free tier = 20 RPD)",
                    ),
                ),
                (
                    "daily_usage",
                    models.IntegerField(default=0, help_text="Requests used today"),
                ),
                (
                    "rpm_limit",
                    models.IntegerField(default=5, help_text="Max requests per minute"),
                ),
                (
                    "last_reset",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date when daily_usage was last reset (Pacific Time)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "gemini_projects",
                "ordering": ["daily_usage"],
            },
        ),
        migrations.CreateModel(
            name="GeminiApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Friendly name (e.g. Key-1)",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="api.geminiproject",
                    ),
                ),
            ],
            options={
                "db_table": "gemini_api_keys",
            },
        ),
    ]
