# Generated by Django 6.0.6 on 2026-07-28 14:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_remove_fraudscanlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("admin_email", models.CharField(max_length=255)),
                ("admin_role", models.CharField(default="super_admin", max_length=50)),
                ("action", models.CharField(max_length=100)),
                ("target_type", models.CharField(blank=True, max_length=50)),
                ("target_id", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.CharField(blank=True, max_length=45)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "admin_audit_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="GroqApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "encrypted_key",
                    models.TextField(help_text="Fernet-encrypted API key"),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "usage_count",
                    models.IntegerField(default=0, help_text="Atomic usage counter"),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "groq_api_keys",
                "ordering": ["usage_count"],
            },
        ),
    ]
