# Generated by Django 6.0.6 on 2026-08-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_adminauditlog_groqapikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="max_salary",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="min_salary",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="salary_currency",
            field=models.CharField(blank=True, default="INR", max_length=10, null=True),
        ),
    ]
